services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: laravel_app
    volumes:
      - ./:/var/www
      - ./docker/app/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/app/local.ini:/usr/local/etc/php/conf.d/local.ini:ro
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
    expose:
      - "9000"

  horizon:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: laravel_horizon
    command: php artisan horizon
    restart: unless-stopped
    volumes:
      - ./:/var/www
    env_file:
      - .env
    depends_on:
      - mysql
      - redis

  scheduler:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: laravel_scheduler
    command: php artisan schedule:work
    restart: unless-stopped
    volumes:
      - ./:/var/www
    env_file:
      - .env
    depends_on:
      - mysql
      - redis

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: laravel_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    container_name: laravel_mysql
    environment:
      MYSQL_DATABASE: deputados_database
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/00-init.sql:ro

  redis:
    build:
      context: ./docker/redis
    container_name: laravel_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
